/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.4.1 scene.gltf --transform
Files: scene.gltf [5.54KB] > /Users/zhangyichun/Documents/Imperial/MSc Individual Project/rare-disease-web-portal/frontend/public/models/dna2/scene-transformed.glb [3.58MB] (-64448%)
Author: Leon_dp (https://sketchfab.com/leondp)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/stylized-simply-visualization-of-dna-51f5ab2ffc364f60be00289eb6909535
Title: Stylized simply visualization of DNA
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export function DnaModel2(props) {
    const { nodes, materials } = useGLTF(
        "../public/models/dna2/scene-transformed.glb"
    );
    return (
        <group {...props} dispose={null}>
            <mesh
                geometry={nodes.defaultMaterial.geometry}
                position={[-500, 350, -600]}
                rotation={[-0.2, 0.4, 3]}
                scale={100}
            >
                <meshStandardMaterial
                    emissive="#8b5cf6"
                    emissiveIntensity={0.5}
                    roughness={0.5}
                    color="#8b5cf6"
                />
            </mesh>
        </group>
    );
}

useGLTF.preload("../public/models/dna2/scene-transformed.glb");
